# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AI语音.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Form")
        MainWindow.resize(721, 679)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        MainWindow.setAcceptDrops(False)
        self.Model = QtWidgets.QComboBox(MainWindow)
        self.Model.setGeometry(QtCore.QRect(70, 290, 110, 22))
        self.Model.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Model.setToolTipDuration(-1)
        self.Model.setEditable(False)
        self.Model.setInsertPolicy(QtWidgets.QComboBox.InsertAlphabetically)
        self.Model.setDuplicatesEnabled(False)
        self.Model.setFrame(True)
        self.Model.setModelColumn(0)
        self.Model.setObjectName("Model")
        self.Model.addItem("")
        self.Model.addItem("")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(MainWindow)
        self.plainTextEdit.setGeometry(QtCore.QRect(70, 210, 110, 21))
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setBackgroundVisible(True)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(MainWindow)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(200, 210, 145, 21))
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setPlaceholderText("")
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.comboBox = QtWidgets.QComboBox(MainWindow)
        self.comboBox.setGeometry(QtCore.QRect(200, 290, 145, 22))
        self.comboBox.setObjectName("模型选择")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(MainWindow)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(365, 210, 150, 21))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.horizontalScrollBar = QtWidgets.QScrollBar(MainWindow)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(365, 290, 150, 20))
        self.horizontalScrollBar.setMinimum(0)
        self.horizontalScrollBar.setMaximum(10)
        self.horizontalScrollBar.setSingleStep(1)
        self.horizontalScrollBar.setPageStep(1)
        self.horizontalScrollBar.setProperty("value", 0)
        self.horizontalScrollBar.setSliderPosition(0)
        self.horizontalScrollBar.setTracking(True)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setInvertedAppearance(False)
        self.horizontalScrollBar.setInvertedControls(True)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.plainTextEdit.raise_()
        self.Model.raise_()
        self.plainTextEdit_2.raise_()
        self.comboBox.raise_()
        self.plainTextEdit_3.raise_()
        self.horizontalScrollBar.raise_()

        self.retranslateUi(MainWindow)
        self.Model.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AI语音"))
        self.Model.setCurrentText(_translate("Form", "符玄"))
        self.Model.setPlaceholderText(_translate("Form", "Model"))
        self.Model.setItemText(0, _translate("Form", "符玄"))
        self.Model.setItemText(1, _translate("Form", "魈"))
        self.plainTextEdit.setPlainText(_translate("Form", "模型选择"))
        self.plainTextEdit_2.setPlainText(_translate("Form", "F0预测器选择"))
        self.comboBox.setItemText(0, _translate("Form", "0：crepe"))
        self.comboBox.setItemText(1, _translate("Form", "1：pm"))
        self.comboBox.setItemText(2, _translate("Form", "2：dio"))
        self.comboBox.setItemText(3, _translate("Form", "3：harvest"))
        self.comboBox.setItemText(4, _translate("Form", "4：rmvpe"))
        self.comboBox.setItemText(5, _translate("Form", "5：fcpe"))
        self.plainTextEdit_3.setPlainText(_translate("Form", "特征检索占比"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)  # 创建一个QApplication，也就是你要开发的软件app
    MainWindow = QtWidgets.QMainWindow()  # 创建一个QMainWindow，用来装载你需要的各种组件、控件
    ui = Ui_MainWindow()  # ui是Ui_MainWindow()类的实例化对象
    ui.setupUi(MainWindow)  # 执行类中的setupUi方法，方法的参数是第二步中创建的QMainWindow
    MainWindow.show()  # 执行QMainWindow的show()方法，显示这个QMainWindow
    sys.exit(app.exec_())  # 使用exit()或者点击关闭按钮退出QApplicat