# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AIKTVUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(470, 20, 321, 411))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.configButton = QtWidgets.QPushButton(self.widget)
        self.configButton.setObjectName("configButton")
        self.verticalLayout_2.addWidget(self.configButton)
        self.chooseRecordGroupBox = QtWidgets.QGroupBox(self.widget)
        self.chooseRecordGroupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.chooseRecordGroupBox.setObjectName("chooseRecordGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.chooseRecordGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chooseRecord = QtWidgets.QPushButton(self.chooseRecordGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseRecord.sizePolicy().hasHeightForWidth())
        self.chooseRecord.setSizePolicy(sizePolicy)
        self.chooseRecord.setObjectName("chooseRecord")
        self.horizontalLayout_2.addWidget(self.chooseRecord)
        self.recordAddress = QtWidgets.QLineEdit(self.chooseRecordGroupBox)
        self.recordAddress.setObjectName("recordAddress")
        self.horizontalLayout_2.addWidget(self.recordAddress)
        self.verticalLayout_2.addWidget(self.chooseRecordGroupBox)
        self.chooseHandledGroupBox = QtWidgets.QGroupBox(self.widget)
        self.chooseHandledGroupBox.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.chooseHandledGroupBox.setObjectName("chooseHandledGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.chooseHandledGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chooseHandled = QtWidgets.QPushButton(self.chooseHandledGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseHandled.sizePolicy().hasHeightForWidth())
        self.chooseHandled.setSizePolicy(sizePolicy)
        self.chooseHandled.setObjectName("chooseHandled")
        self.horizontalLayout.addWidget(self.chooseHandled)
        self.handledAddress = QtWidgets.QLineEdit(self.chooseHandledGroupBox)
        self.handledAddress.setObjectName("handledAddress")
        self.horizontalLayout.addWidget(self.handledAddress)
        self.verticalLayout_2.addWidget(self.chooseHandledGroupBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.configButton.setText(_translate("MainWindow", "AI模型配置"))
        self.chooseRecordGroupBox.setTitle(_translate("MainWindow", "选择录音文件"))
        self.chooseRecord.setText(_translate("MainWindow", "选择文件"))
        self.chooseHandledGroupBox.setTitle(_translate("MainWindow", "选择处理后文件"))
        self.chooseHandled.setText(_translate("MainWindow", "选择文件"))
